name: "AniDB"
guid: "a2b2a7ed-aa28-4521-a64a-63d86901f246"
imageUrl: https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anidb.png
version: 8
targetAbi: "10.8.5.0"
framework: "net6.0"
owner: "jellyfin"
overview: "AniDB metadata provider"
description: >
  AniDB metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniDB.dll"
changelog: |2-
  ### New features and improvements ###
  - Make series.xml cache age user configurable (#44) @Scholars-Mate

  ### Bug Fixes ###
  - Detect api errors and throw exception (#42) @Nalsai
